/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Agendamento;
import model.Medico;
import model.Paciente;
import services.AgendamentoServico;
import services.MedicoServico;
import services.PacienteServico;

/**
 *
 * @author zanna
 */
public class DadosAgendamento extends javax.swing.JFrame {

    private Agendamento agendamento;
    private Paciente paciente;

    /**
     * Creates new form DadosAgendamento
     */
    public DadosAgendamento(Agendamento agendamento) {
        initComponents();
        carregarMedicosCombo();
        if (agendamento != null) {
            carregarAgendamento(agendamento);
        }
    }

    private void carregarAgendamento(Agendamento agendamento) {
        this.agendamento = agendamento;

        // Carregar Paciente
        this.paciente = this.agendamento.getPaciente();
        if (this.paciente != null) {
            campo_pac_nome.setText(this.paciente.getNome());
        }

        // Carregar Medico
        Medico medico = this.agendamento.getMedico();
        if (medico != null) {
            combo_medico.setSelectedItem(medico);
            campo_med_especialidade.setText(medico.getEspecialidades());
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        campo_ag_data.setText(dateFormat.format(this.agendamento.getDataHora().getTime()));

        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        campo_ag_horario.setText(timeFormat.format(this.agendamento.getDataHora().getTime()));
        
        botao_ag_agendar.setText("Atualizar");
    }

    private void carregarMedicosCombo() {
        MedicoServico servico = new MedicoServico();
        ArrayList<Medico> lista_medicos = servico.consultarTodos();

        if (lista_medicos != null) {
            for (Medico medico : lista_medicos) {
                combo_medico.addItem(medico);
            }

            Medico medicoIndexZero = (Medico) combo_medico.getItemAt(0);

            if (medicoIndexZero != null) {
                campo_med_especialidade.setText(medicoIndexZero.getEspecialidades());
            }

            combo_medico.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    campo_med_especialidade.setText("");
                    Medico medicoSelecionado = (Medico) combo_medico.getSelectedItem();
                    if (medicoSelecionado != null) {
                        campo_med_especialidade.setText(medicoSelecionado.getEspecialidades());
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_pac_cpf = new javax.swing.JTextField();
        botao_pac_consultar = new javax.swing.JButton();
        campo_pac_nome = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        combo_medico = new javax.swing.JComboBox<>();
        campo_med_especialidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campo_ag_data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campo_ag_horario = new javax.swing.JTextField();
        botao_ag_agendar = new javax.swing.JButton();
        botao_ag_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CPF");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Paciente");

        campo_pac_cpf.setBackground(new java.awt.Color(255, 255, 255));
        campo_pac_cpf.setForeground(new java.awt.Color(51, 51, 51));
        campo_pac_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_pac_cpfActionPerformed(evt);
            }
        });

        botao_pac_consultar.setBackground(new java.awt.Color(51, 0, 255));
        botao_pac_consultar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        botao_pac_consultar.setForeground(new java.awt.Color(255, 255, 255));
        botao_pac_consultar.setText("Consultar");
        botao_pac_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pac_consultarActionPerformed(evt);
            }
        });

        campo_pac_nome.setBackground(new java.awt.Color(255, 255, 255));
        campo_pac_nome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        campo_pac_nome.setForeground(new java.awt.Color(51, 51, 51));
        campo_pac_nome.setEnabled(false);
        campo_pac_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_pac_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_pac_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_pac_consultar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_pac_nome)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_pac_cpf)
                    .addComponent(botao_pac_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(campo_pac_nome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Médico");

        combo_medico.setBackground(new java.awt.Color(255, 255, 255));
        combo_medico.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        combo_medico.setForeground(new java.awt.Color(51, 51, 51));

        campo_med_especialidade.setBackground(new java.awt.Color(255, 255, 255));
        campo_med_especialidade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        campo_med_especialidade.setForeground(new java.awt.Color(51, 51, 51));
        campo_med_especialidade.setEnabled(false);
        campo_med_especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_med_especialidadeActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Especialidade");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_med_especialidade)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_med_especialidade))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Data:");

        campo_ag_data.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Horário:");

        campo_ag_horario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_ag_data, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_ag_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_ag_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel5))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campo_ag_data, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botao_ag_agendar.setBackground(new java.awt.Color(51, 0, 255));
        botao_ag_agendar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botao_ag_agendar.setForeground(new java.awt.Color(255, 255, 255));
        botao_ag_agendar.setText("Agendar");
        botao_ag_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ag_agendarActionPerformed(evt);
            }
        });

        botao_ag_cancelar.setBackground(new java.awt.Color(51, 0, 204));
        botao_ag_cancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botao_ag_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        botao_ag_cancelar.setText("Cancelar");
        botao_ag_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ag_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_ag_agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_ag_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_ag_agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_ag_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_pac_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_pac_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_pac_cpfActionPerformed

    private void botao_pac_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pac_consultarActionPerformed
        if (campo_pac_cpf.getText().isEmpty()) {
            // Exibe uma mensagem de alerta informando que o campo de CPF do paciente está vazio
            JOptionPane.showMessageDialog(null, "Campo nome vazio");
            // Define o foco no campo para preencher
            campo_pac_cpf.requestFocus();
            return; // Sai do método, pois a validação falhou
        }

        PacienteServico servico = new PacienteServico();
        Paciente paciente = servico.consultarPorCPF(campo_pac_cpf.getText());

        campo_pac_nome.setText("");
        if (paciente != null) {
            this.paciente = paciente;
            campo_pac_nome.setText(paciente.getNome());
        } else {
            JOptionPane.showMessageDialog(null, "Paciente não encontrado.");
            // Define o foco no campo para preencher
            campo_pac_cpf.requestFocus();
        }
    }//GEN-LAST:event_botao_pac_consultarActionPerformed

    private void campo_pac_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_pac_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_pac_nomeActionPerformed

    private void botao_ag_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ag_agendarActionPerformed

        if (this.paciente == null) {
            JOptionPane.showMessageDialog(null, "Consulta um Paciente para agendar.");
            campo_pac_cpf.requestFocus();
            return;
        }

        Medico medicoSelecionado = (Medico) combo_medico.getSelectedItem();
        if (medicoSelecionado == null) {
            JOptionPane.showMessageDialog(null, "Consulta um Medico para agendar.");
            return;
        }

        String dateString = campo_ag_data.getText();
        String timeString = campo_ag_horario.getText();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");

        try {
            Date date = dateFormat.parse(dateString);
            Date time = timeFormat.parse(timeString);

            // Combinar data e hora
            Calendar dateTime = Calendar.getInstance();
            Calendar currentDate = Calendar.getInstance();

            dateTime.setTime(date);
            dateTime.set(Calendar.HOUR_OF_DAY, time.getHours());
            dateTime.set(Calendar.MINUTE, time.getMinutes());
            dateTime.set(Calendar.SECOND, time.getSeconds());

            // Comparar com a data e hora atuais
            if (dateTime.before(currentDate)) {
                JOptionPane.showMessageDialog(this, "Não é possível agendar em uma data anterior.", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                AgendamentoServico servico = new AgendamentoServico();
                if (this.agendamento == null) {
                    if (servico.agendar(medicoSelecionado, paciente, dateTime)) {
                        JOptionPane.showMessageDialog(null, "Agendamento realizado com sucesso.");
                        this.dispose();
                        Home view = new Home();
                        view.setVisible(true);
                    }
                } else {
                    if (servico.reagendar(this.agendamento, medicoSelecionado, paciente, dateTime)) {
                        JOptionPane.showMessageDialog(null, "Agendamento atualizado com sucesso.");
                        this.dispose();
                        Home view = new Home();
                        view.setVisible(true);
                    }
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato de data ou hora inválido", "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botao_ag_agendarActionPerformed

    private void botao_ag_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ag_cancelarActionPerformed
        this.dispose();
        // Instancia e exibe a tela principal
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_botao_ag_cancelarActionPerformed

    private void campo_med_especialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_med_especialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_med_especialidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosAgendamento(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_ag_agendar;
    private javax.swing.JButton botao_ag_cancelar;
    private javax.swing.JButton botao_pac_consultar;
    private javax.swing.JTextField campo_ag_data;
    private javax.swing.JTextField campo_ag_horario;
    private javax.swing.JTextField campo_med_especialidade;
    private javax.swing.JTextField campo_pac_cpf;
    private javax.swing.JTextField campo_pac_nome;
    private javax.swing.JComboBox<Medico> combo_medico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
