/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Usuario;
import services.UsuarioServico;

/**
 *
 * @author zanna
 */
public class ListaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ListaUsuario
     */
    public ListaUsuario() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTUsuario.getModel();
        jTUsuario.setRowSorter(new TableRowSorter(modelo));

        UsuarioServico servico = new UsuarioServico();
        carregarUsuariosNaTabela(servico.consultarTodos());
    }

    private void carregarUsuariosNaTabela(ArrayList<Usuario> list) {
        // Limpar dados da Tabela
        DefaultTableModel modelo = (DefaultTableModel) jTUsuario.getModel();
        modelo.setNumRows(0);

        if (list != null) {
            for (Usuario p : list) {

                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getLogin(),
                    p.getSenha(),
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_novo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo_pesquisa = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuario = new javax.swing.JTable();
        btn_excluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(908, 501));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/logoofc1.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Lista de Usuarios");

        btn_novo.setBackground(new java.awt.Color(51, 0, 255));
        btn_novo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_novo.setForeground(new java.awt.Color(255, 255, 255));
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/novo-arquivo.png"))); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(51, 0, 255));
        btn_editar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/editar.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pesquisar:");

        campo_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        campo_pesquisa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnConsulta.setBackground(new java.awt.Color(51, 0, 255));
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/lupa.png"))); // NOI18N
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        jTUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTUsuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jTUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Login", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTUsuario.setShowGrid(true);
        jTUsuario.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTUsuario);
        if (jTUsuario.getColumnModel().getColumnCount() > 0) {
            jTUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTUsuario.getColumnModel().getColumn(1).setResizable(false);
            jTUsuario.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_excluir.setBackground(new java.awt.Color(51, 0, 255));
        btn_excluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/excluir.png"))); // NOI18N
        btn_excluir.setText("excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(51, 0, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/limpeza-de-dados.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        botao_cancelar.setBackground(new java.awt.Color(51, 0, 204));
        botao_cancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botao_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        botao_cancelar.setText("Cancelar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_novo)
                                .addGap(4, 4, 4)
                                .addComponent(btn_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botao_cancelar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_novo)
                            .addComponent(btn_editar)
                            .addComponent(jLabel2)
                            .addComponent(campo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsulta)
                            .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_cancelar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        this.dispose();// Fecha a janela atual
        DadosUsuario view = new DadosUsuario(null);// Abre a tela de cadastro de um novo usuário
        view.setVisible(true);// Torna a nova tela visível
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // Verifica se uma linha está selecionada
        if (jTUsuario.getSelectedRow() != -1) {
            int id = (int) jTUsuario.getValueAt(jTUsuario.getSelectedRow(), 0);// Obtém o ID do usuário selecionado
            UsuarioServico servico = new UsuarioServico();
            Usuario usuario = servico.consultarPorId(id);// Consulta o usuário pelo ID
            this.dispose();// Fecha a janela atual
            DadosUsuario view = new DadosUsuario(usuario);// Abre a tela de edição com os dados do usuário
            view.setVisible(true);// Torna a nova tela visível
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para editar.");// Mostra mensagem de erro
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        if (campo_pesquisa.getText().isEmpty()) { // Verifica se o campo de pesquisa está vazio
            JOptionPane.showMessageDialog(null, "Campo de pesquisa vazio");// Mostra mensagem de erro
            // Define o foco no campo de nome para o usuário preencher
            campo_pesquisa.requestFocus();
            return;
        }

        UsuarioServico servico = new UsuarioServico();
        ArrayList<Usuario> pacientes = servico.filtrar(campo_pesquisa.getText());// Filtra os usuários pelo texto de pesquisa
        carregarUsuariosNaTabela(pacientes);// Carrega os usuários na tabela
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        if (jTUsuario.getSelectedRow() != -1) { // Verifica se uma linha está selecionada
            int id = (int) jTUsuario.getValueAt(jTUsuario.getSelectedRow(), 0);// Obtém o ID do usuário selecionado

            int confirmacao = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja deletar este registro?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmacao == JOptionPane.YES_OPTION) { // Verifica a confirmação do usuário
                UsuarioServico servico = new UsuarioServico();
                servico.deletar(id);// Deleta o usuário
                JOptionPane.showMessageDialog(null, "Usuario removido com sucesso."); // Mostra mensagem de sucesso
                carregarUsuariosNaTabela(servico.consultarTodos());// Recarrega a tabela
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para deletar."); // Mostra mensagem de erro
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        campo_pesquisa.setText(""); // Limpa o campo de pesquisa
        UsuarioServico servico = new UsuarioServico();
        carregarUsuariosNaTabela(servico.consultarTodos());// Recarrega a tabela com todos os usuários
    }//GEN-LAST:event_btnLimparActionPerformed

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
            this.dispose();// Fecha a janela atual
            Home home = new Home();// Abre a tela principal
            home.setVisible(true); // Torna a tela principal visível       
    }//GEN-LAST:event_botao_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JTextField campo_pesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUsuario;
    // End of variables declaration//GEN-END:variables
}
